### ISSUE TITLE
NAT gateway timing issue

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#791] opened 2019-05-23 22:14 UTC
/kind bug

Possibly related to #241

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Create a cluster
2. Delete it
3. Recreate the cluster using the same manifests again

This results in a new NAT gateway being created, but the old deleted NAT gateway being attached to the routing tables. This occurs because the deleted NAT gateway remains visible in the API for 60 minutes after deletion, and we are probably not filtering correctly.

**What did you expect to happen:**
Cluster should be recreated

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: HEAD
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by aaroniscode** [comment] 2019-06-04 20:30
I’m going to see if I can reproduce this issue and try to identify root cause

**Comment by aaroniscode** [comment] 2019-08-13 20:17
I have not been able to reproduce this and have created/deleted a good number of clusters.

**Comment by detiber** [comment] 2019-08-13 20:29
Yay, thank you for attempting to reproduce the issue. I'm going to go ahead and close this issue then :)

/close

**Closed by detiber** 2019-08-13 20:29 UTC
Labels: kind/bug, priority/important-soon
