### ISSUE TITLE
the cluster network field always has been overwrite 

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#1143] opened 2019-09-23 02:17 UTC
/kind bug

if the user set a tag to the subnet of the cluster, and the CAPA controller will overwrite the tag always.

```go
func (s *Service) getSubnetTagParams(id string, public bool) v1alpha1.BuildParams {
    var role string
    var additionalTags v1alpha1.Tags

    // Add tag needed for Service type=LoadBalancer
    additionalTags = v1alpha1.Tags{
        v1alpha1.NameKubernetesAWSCloudProviderPrefix + s.scope.Name(): string(v1alpha1.ResourceLifecycleShared),
    }

    if public {
        role = v1alpha1.PublicRoleTagValue
    } else {
        role = v1alpha1.PrivateRoleTagValue
    }

    var name strings.Builder
    name.WriteString(s.scope.Name())
    name.WriteString("-subnet-")
    name.WriteString(role)

    return v1alpha1.BuildParams{
        ClusterName: s.scope.Name(),
        ResourceID:  id,
        Lifecycle:   v1alpha1.ResourceLifecycleOwned,
        Name:        aws.String(name.String()),
        Role:        aws.String(role),
        Additional:  additionalTags,
    }
}
```

**Comment by detiber** [comment] 2019-09-23 14:01
@Sn0rt Just to clarify are you expecting that a user would set a tag on a CAPA managed subnet externally and for that tag to not be removed during future reconciliation?

Or is the issue that we are not respecting the Tags defined in Cluster.Spec.NetworkSpec.Subnets[*].Tags?

**Comment by vincepri** [comment] 2019-09-23 14:27
This seems like a duplicate of #1142, or at least gives more information to solve the other issue

**Comment by liztio** [comment] 2019-10-04 21:31
/assign 
/lifecycle active

I dug this up as part of #1142, I will drop a solution soon

**Closed** 2019-10-08 14:33 UTC
Labels: kind/bug, lifecycle/active, priority/awaiting-more-evidence
