### ISSUE TITLE
in release-0.4 branch make create-cluster-management fails

### ISSUE THREAD

**Issue by luigi-riefolo** [kubernetes-sigs/cluster-api-provider-aws#1300] opened 2019-10-30 17:35 UTC
/kind bug

**What steps did you take and what happened:**
in branch `release-0.4` running `make create-cluster-management` produces the following error:

```unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
Makefile:310: recipe for target 'create-cluster-management' failed
make: *** [create-cluster-management] Error 1
```

**What did you expect to happen:**
`make create-cluster-management` to successfully create a development Kubernetes cluster on AWS in a KIND management cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: release-0.4
- Kubernetes version: (use `kubectl version`):  `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by tahsinrahman** [comment] 2019-11-01 03:48
@luigi-riefolo I can't reproduce it in release-0.4 branch. Can you check again? Also, make sure you've don't have `CAPI_BRANCH` env var set

**Comment by luigi-riefolo** [comment] 2019-11-01 11:36
@tahsinrahman thanks, the `CAPI_BRANCH` was not set.

I did a git pull and this is what I'm encountering now:

```
I1101 11:28:29.532937   10904 clusterclient.go:242] Waiting to acquire client... server not yet available: Get https://test1-apiserver-XXXXXXXXX.eu-west-2.elb.amazonaws.com:6443/api?timeout=32s: EOF
F1101 11:28:29.533047   10904 alpha_phase_apply_addons.go:51] unable to create cluster client: failed to acquire new client: timed out waiting for the condition
Makefile:310: recipe for target 'create-cluster-management' failed
```

any idea?

**Comment by ncdc** [comment] 2019-11-07 15:59
There is a new issue with this in `release-0.4` because of an `${IMAGE_ID}` placeholder that was recently added for e2e conformance testing. I have opened #1336 to fix this.

**Comment by ncdc** [comment] 2019-11-07 19:27
Now that #1336 has merged, you should be able to do `make create-cluster-management` again. Please open a new issue if you encounter future problems (as this issue has already bounced around a bit for different root causes).

/close

**Closed by ncdc** 2019-11-07 19:27 UTC
Labels: kind/bug, priority/important-soon
