### ISSUE TITLE
Permission denied looking up AMIs

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api-provider-aws#497] opened 2019-01-16 17:50 UTC
/kind bug

**What steps did you take and what happened:**
Running a "dev" version of the aws controller that included #479 (and again with #488) I was unable to look up the AMI required to create EC2 instances.

**What did you expect to happen:**
EC2 instances to be created based on the looked-up AMI

**Anything else you would like to add:**

The log message I saw from the controller:

```
I0115 19:11:56.931055       1 instances.go:96] Creating a new instance for machine "controlplane-0"
W0115 19:11:57.096440       1 controller.go:183] unable to create machine controlplane-0: failed to create or get machine: UnauthorizedOperation: You are not authorized to perform this operation.
    status code: 403, request id: 4c261bbc-447a-4a1a-93d5-950a703f11b3
failed to find ami: "ami-ubuntu-18.04-1.13.0-??-??????????"
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/ec2.(*Service).defaultAMILookup
    pkg/cloud/aws/services/ec2/ami.go:78
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/ec2.(*Service).createInstance
    pkg/cloud/aws/services/ec2/instances.go:115
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/ec2.(*Service).CreateOrGetMachine
    pkg/cloud/aws/services/ec2/instances.go:305
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine.(*Actuator).Create
    pkg/cloud/aws/actuators/machine/actuator.go:151
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine.(*ReconcileMachine).create
    vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go:199
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine.(*ReconcileMachine).Reconcile
    vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go:182
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
    vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
    vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
    vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.Until
    vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
runtime.goexit
    bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib%/src/runtime/asm_amd64.s:1333
```

I haven't tried to reproduce the issue with any other AWS tooling yet, but as reverting 32e87fe allowed me to create clusters, it appears that I had sufficient permission for every part besides the AMI lookup.

**Environment:**

- Cluster-api-provider-aws version: c775f130c01c99c49fd7
- Kubernetes version: (use `kubectl version`): 1.12.1
- OS (e.g. from `/etc/os-release`): macOS running minikube

**Comment by sethp-nr** [comment] 2019-01-16 18:37
Of course! Feel free to ping me here or on slack if you'd like me to try something.

**Comment by randomvariable** [comment] 2019-01-16 19:31
Root cause documented in #495

**Comment by chuckha** [comment] 2019-01-19 16:18
closed by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/500

**Closed by chuckha** 2019-01-19 16:18 UTC
Labels: kind/bug, priority/critical-urgent
