### ISSUE TITLE
Stopping a bastion instance leads to CAPA creating a second bastion instance

### ISSUE THREAD

**Issue by ashoksekar07** [kubernetes-sigs/cluster-api-provider-aws#1704] opened 2020-04-28 20:56 UTC
/kind bug

**What steps did you take and what happened:**
Create a cluster using CAPA. Go to AWS console and stop the bastion instance.

**What did you expect to happen:**
CAPA should reconcile this bastion instance and start it again. Or create a new one and delete the existing instance.

But CAPA left the old instance as such and created a new instance which I don't think is the ideal behavior.

**Environment:**

- Cluster-api-provider-aws version: 0.4.10
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`):  Amazon Linux 2

**Comment by randomvariable** [comment] 2020-04-29 11:32
Dupe of #1703

**Closed by randomvariable** 2020-04-29 11:32 UTC
Labels: kind/bug
