### ISSUE TITLE
Slow down retries if EC2 public key isn't available

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#202] opened 2018-10-09 11:54 UTC
/kind feature

**Describe the solution you'd like**

It's likely that a user may forget to upload an EC2 public key.

The create instance method used by both actuators returns an error and the object
gets requeued immediately, retried 10 times and then errors out.

We should use mark this as failed dependency and then requeue with a 1m delay
giving time for the user to rectify the error in a reasonable time frame and
not have to wait for a later reconciliation loop.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by chuckha** [comment] 2018-11-16 15:14
I think this got fixed here https://github.com/kubernetes-sigs/cluster-api/commit/2d88aefcf94fcffbf647fcc1127a642112714b2f#diff-b96ce5bf8686fb02d855188000ae1cb4

If you can reproduce thought please lmk

**Comment by vincepri** [comment] 2019-01-02 18:39
Closing this because seems to be fixed as @chuckha pointed out. Feel free to reopen if not.

/close

**Closed by vincepri** 2019-01-02 18:39 UTC
Labels: kind/feature, priority/awaiting-more-evidence
